/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: RunemarkStudio (https://sketchfab.com/runemarkstudio)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/pin-for-3d-clothing-47512c994e70431d853a9e3dcaa3baba
title: Pin for 3D clothing
*/

import React, { useRef } from "react";
import { useFrame } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";

export default function Pin(props: any): JSX.Element {
  const { nodes, materials } = useGLTF("/pin.glb");
  const group = useRef<THREE.Group>();
  //   useFrame((state, delta) => {
  //   if (group.current) {
  //     group.current.rotation.y -= 0.001;
  //   }
  //   });

  return (
    <group {...props} dispose={null} ref={group}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          //   @ts-ignore
          geometry={nodes.Object_2.geometry}
          material={materials.None}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/pin.glb");
